default: &default
  adapter: mysql
  pool: 5
  timeout: 5000
  database: <%= PRIVATE['database']['database'] %>
  username: <%= PRIVATE['database']['username'] %>
  password: <%= PRIVATE['database']['password'] %>
  host: <%= PRIVATE['database']['host'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

